src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $category_name = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Product::class)]
    private Collection $product;

    public function __construct()
    {
        $this->product = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoryName(): ?string
    {
        return $this->category_name;
    }

    public function setCategoryName(string $category_name): self
    {
        $this->category_name = $category_name;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProduct(): Collection
    {
        return $this->product;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->product->contains($product)) {
            $this->product->add($product);
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->product->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }
}

src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping as ORM;
use Stripe\Checkout\Session;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    const STATUS_CART = false;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(inversedBy: 'order_cart', cascade: ['persist', 'remove'])]
    private ?User $user = null;

    #[ORM\Column]
    private ?bool $status = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\OneToMany(mappedBy: 'assocOrder', targetEntity: CartItem::class, orphanRemoval: true, cascade:['persist'])]
    private Collection $items;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?PaymentDetail $paymentDetail = null;

    #[ORM\Column(length: 255, nullable:true)]
    private ?string $stripe_session = null;

    #[ORM\OneToMany(mappedBy: 'loggedOrder', targetEntity: InventoryLog::class, orphanRemoval: true)]
    private Collection $inventoryLogs;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Cities $city = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Countries $country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $addressLine1 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $addressLine2 = null;

    #[ORM\Column(length: 12, nullable: true)]
    private ?string $postalCode = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $state = null;

    #[ORM\Column(length: 17, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $customerName = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $session_expiration = null;

    #[ORM\Column(length: 15, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(length: 15, nullable: true)]
    private ?string $paymentType = null;

    #[ORM\Column(nullable:true)]
    private ?bool $paid = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Discount $discount = null;

    public function __construct()
    {
        $this->items = new ArrayCollection();
        $this->inventoryLogs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, CartItem>
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(CartItem $item): self
    {
        foreach($this->items as $existingItem){
            if ($existingItem->equals($item)) {
                $existingItem->setQuantity(
                    $existingItem->getQuantity() + $item->getQuantity()
                );
                return $this;
            }
        }
        $this->items->add($item);
        $item->setAssocOrder($this);


        return $this;
    }

    public function removeItem(CartItem $item): self
    {
        if ($this->items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getAssocOrder() === $this) {
                $item->setAssocOrder(null);
            }
        }

        return $this;
    }
    /**
     * Removes all items from the order.
     *
     * @return $this
     */
    public function removeItems(): self
    {
        foreach ($this->getItems() as $item) {
            $this->removeItem($item);
        }

        return $this;
    }
    /**
     * Calculates the order total.
     *
     * @return float
     */
    public function getTotal(): float
    {
        $total = 0;

        foreach ($this->getItems() as $item) {
            $total += $item->getTotal();
        }

        return $total;
    }

    /**
     * Calculates the order total with discount.
     *
     * @return float
     */
    public function getTotalWithDiscount(): float
    {
        $total = 0;

        foreach ($this->getItems() as $item) {
            $total += $item->getTotal();
        }

        if($this->getDiscount()!=null){
            $discountAmount=$this->getDiscount()->getDiscountAmount($total);
            $total-=$discountAmount;
        }

        return $total;
    }

    public function getPaymentDetail(): ?PaymentDetail
    {
        return $this->paymentDetail;
    }

    public function setPaymentDetail(?PaymentDetail $paymentDetail): self
    {
        $this->paymentDetail = $paymentDetail;

        return $this;
    }

    public function getStripeSession(): ?string
    {
        return $this->stripe_session;
    }

    public function setStripeSession(string $stripe_session=null): self
    {
        $this->stripe_session = $stripe_session;

        return $this;
    }

    public function removeInventory(EntityManagerInterface $entityManager): self{
        foreach($this->getItems() as $item){
            $pi=$item->getProduct()->getHighestInventory();
            $loggedPI=new InventoryLog();
            $itemQuantity=$item->getQuantity();
            $remainingQuantity=$pi->getQuantity()-$itemQuantity;
            $loggedPI->setAmount($itemQuantity);
            $loggedPI->setLoggedInv($pi);
            $loggedPI->setLoggedOrder($this);
            $entityManager->persist($loggedPI);
            $pi->setQuantity($remainingQuantity);
        }
        $entityManager->flush();
        return $this;
    }
    public function returnInventory(EntityManagerInterface $entityManager): self{
        // TODO: ADD NEW LOCATION ENTITY WITH AMOUNT OF "DEBT" FROM EACH ORDER
        // TODO: Add an order ID (maybe use the invoice id)
        // TODO: IF LOGGED INV GETS DELETED, CHECK FOR ISSUES (MIGHT HAVE TO MAKE IT SO THE PRODUCT GETS ALL LOCATIONS CREATED AND STORED EVEN IF THERE IS NO PRODUCTS THERE)
        foreach($this->getInventoryLogs() as $item){
            $pi=$item->getLoggedInv();
            $pi->setQuantity($pi->getAmount()+$item->getQuantity());
        }
        $entityManager->flush();
        return $this;
    }
    public function finishOrder(EntityManagerInterface $entityManager): self {
        if($this->paymentType=="cash"){
//            $this->setStripeSession(null);
        }
        if($this->getStripeSession()!=null){
            $session = Session::retrieve($this->getStripeSession())->customer_details;
            $time=new \DateTimeImmutable();
            $this->setUpdatedAt($time);
            $country=$entityManager->getRepository(Countries::class)->findOneBy(['iso2'=>$session['address']['country']]);
            $city=$entityManager->getRepository(Cities::class)->findOneBy(['name'=>$session['address']['city'],'country_code'=>$session['address']['country']]);
            $this->setCountry($country);
            $this->setCity($city);
            $this->setAddressLine1($session['address']['line1']);
            $this->setAddressLine2($session['address']['line2']);
            $this->setPostalCode($session['address']['postal_code']);
            $this->setState($session['address']['state']);
            $this->setCustomerName($session['name']);
//            dd($session['customer_details']);
//            $this->setPhone($session['customer_details']['phone']);
        }
        foreach($this->getInventoryLogs() as $item){
            $this->removeInventoryLog($item);
        }
        $this->setStatus(true);
        $entityManager->flush();
        return $this;
    }

    /**
     * @return Collection<int, InventoryLog>
     */
    public function getInventoryLogs(): Collection
    {
        return $this->inventoryLogs;
    }

    public function addInventoryLog(InventoryLog $inventoryLog): self
    {
        if (!$this->inventoryLogs->contains($inventoryLog)) {
            $this->inventoryLogs->add($inventoryLog);
            $inventoryLog->setLoggedOrder($this);
        }

        return $this;
    }

    public function removeInventoryLog(InventoryLog $inventoryLog): self
    {
        if ($this->inventoryLogs->removeElement($inventoryLog)) {
            // set the owning side to null (unless already changed)
            if ($inventoryLog->getLoggedOrder() === $this) {
                $inventoryLog->setLoggedOrder(null);
            }
        }

        return $this;
    }

    public function getCity(): ?Cities
    {
        return $this->city;
    }

    public function setCity(?Cities $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?Countries
    {
        return $this->country;
    }

    public function setCountry(?Countries $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getAddressLine1(): ?string

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Positive;
use Symfony\Component\Validator\Constraints\Range;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name',null,[
                'constraints' => [
                    new NotBlank(),
                ]
            ])
            ->add('shortDesc',HiddenType::class)
            ->add('description',HiddenType::class)
            ->add('SKU',null,[
                'label' => 'SKU Code',
                'attr' => ['class'=>'rounded col-5 ms-5'],
                'label_attr' => ['class'=>'col-5 ms-5'],
                ])
            ->add('thumbnail', FileType::class, [
                'label' => 'Thumbnail (Image)',

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                            'image/jpg'
                        ],
                        'mimeTypesMessage' => 'Please upload a valid image! (PNG/JPEG/JPG)',
                    ])
                ],
            ])
            ->add('productImages',CollectionType::class,[
                // each entry in the array will be an "email" field
                'entry_type' => FileType::class,
                'entry_options'=>[
                    'constraints'=>[
                        new File([
                            'maxSize' => '1024k',
                            'mimeTypes' => [
                                'image/jpeg',
                                'image/png',
                                'image/jpg'
                            ],
                            'mimeTypesMessage' => 'Please upload a valid image! (PNG/JPEG/JPG)',
                        ])
                   ],
                    'attr' => ['class' => 'image-box'],
                    'label'=>false,
                ],
                'allow_add' => true,
                'prototype' => true,
                'attr' => ['id'=>'imgdiv'],
                'required' => false,
            ])
            ->add('seller')
            ->add('price',null,[
                'attr' => ['class'=>'rounded col-5 ms-0'],
                'label_attr' => ['class'=>'col-5 ms-0'],
                'constraints' => [
                    new Positive()
                ],
            ])
            ->add('status', ChoiceType::class,[
                'choices' => [
                    'Draft' => 0,
                    'In Stock' => 1,
                    'Out of Stock' => 2,
                    ],
                'constraints' => [
                    new Range([
                        'min' => 0,
                        'max' => 2,
                        'notInRangeMessage' => 'You must be between {{ min }} and {{ max }} for status to work.',
                    ])
                ],
            ])
            ->add('productInventories',CollectionType::class,[
                // each entry in the array will be an "email" field
                'entry_type' => ProductInventoryType::class,
                'allow_add' => true,
                'prototype' => true,
                // these options are passed to each "email" type
                'entry_options' => [
                    'attr' => ['class' => 'inventory-box'],
                    ],
                    'attr' => ['id'=>'locdiv'],
                    ])
//            ->add('locations')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
            'inherit_data' => true,
            'productInventories'=>null,
        ]);
    }
}

templates/products/cart.html.twig
{% extends 'base.html.twig' %}

{% block title %}PCStore Cart{% endblock %}

{% form_theme discountForm 'products/cart_error.html.twig' %}

{% block navhome %}
    active
{% endblock %}
{% block bodystyle %}
    style="background-color: black"
{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="/css/order.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}
{% block headerdiv %}{% endblock %}

{% block body %}
    <div class="container">
        {% if cart.type is empty or cart.paymentType is empty %}
            <span id="updateOrder"></span>
        {% endif %}
        <span></span>
        <!-- HERO SECTION-->
        <section class="py-5 bg-light">
            <div class="container">
                <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
                    <div class="col-lg-6">
                        <h1 class="h2 text-uppercase mb-0">Cart</h1>
                    </div>
                    <div class="col-lg-6 text-lg-end">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-lg-end mb-0 px-0 bg-light">
                                <li class="breadcrumb-item"><a class="text-dark" href="{{ path('app_index') }}">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Cart</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </section>
        <section class="py-5">
            <h2 class="h5 text-uppercase mb-4">Shopping cart</h2>
            {% if cart.items is empty %}
                Your current cart is empty.
            {% else %}
            <div class="row">
                <div class="col-lg-8 mb-4 mb-lg-0">
                    <!-- CART TABLE-->

                    <div class="table-responsive mb-4">
                        <table class="table text-nowrap">
                            <thead class="bg-light">
                            <tr>
                                <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase">Product</strong></th>
                                <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase">Price</strong></th>
                                <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase">Quantity</strong></th>
                                <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase">Total</strong></th>
                                <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase"></strong></th>
                            </tr>
                            </thead>
                            <tbody class="border-0">
                            {% include 'element_templates/order_items.html.twig' with {'cart': cart} %}
{#                            <tr>#}
{#                                <th class="ps-0 py-3 border-0" scope="row">#}
{#                                    <div class="d-flex align-items-center"><a class="reset-anchor d-block animsition-link" href="detail.html"><img src="https://d19m59y37dris4.cloudfront.net/boutique/2-0/img/product-detail-2.62056b28.jpg" alt="..." width="70"></a>#}
{#                                        <div class="ms-3"><strong class="h6"><a class="reset-anchor animsition-link" href="detail.html">Apple watch</a></strong></div>#}
{#                                    </div>#}
{#                                </th>#}
{#                                <td class="p-3 align-middle border-0">#}
{#                                    <p class="mb-0 small">$250</p>#}
{#                                </td>#}
{#                                <td class="p-3 align-middle border-0">#}
{#                                    <div class="border d-flex align-items-center justify-content-between px-3"><span class="small text-uppercase text-gray headings-font-family">Quantity</span>#}
{#                                        <div class="quantity">#}
{#                                            <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button>#}
{#                                            <input class="form-control form-control-sm border-0 shadow-0 p-0" type="text" value="1">#}
{#                                            <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </td>#}
{#                                <td class="p-3 align-middle border-0">#}
{#                                    <p class="mb-0 small">$250</p>#}
{#                                </td>#}
{#                                <td class="p-3 align-middle border-0"><a class="reset-anchor" href="#!"><i class="fas fa-trash-alt small text-muted"></i></a></td>#}
{#                            </tr>#}
                            </tbody>
                        </table>
                    </div>
                    <!-- CART NAV-->
                    <div class="bg-light px-4 py-3">
                        <div class="row align-items-center text-center">
                            <div class="col-md-6 mb-3 mb-md-0 text-md-start"><a class="btn btn-link p-0 text-dark btn-sm" href="shop.html"><i class="fas fa-long-arrow-alt-left me-2"> </i>Continue shopping</a></div>
                            <div class="col-md-6 text-md-end">
                                    <form id='checkout-form' method='post' action="{{ path('app_stripe_checkout') }}">
                                        <button type="submit" class="btn btn-outline-dark btn-sm">Procceed to checkout<i class="fas fa-long-arrow-alt-right ms-2"></i></button>
                                    </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- ORDER TOTAL-->
                <div class="col-lg-4">
                    <div class="card border-0 rounded-0 p-lg-4 bg-light">
                        <div class="card-body">
                            <h5 class="text-uppercase mb-4">Cart total</h5>
                            <ul class="list-unstyled mb-0">
                                <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Subtotal</strong><span class="text-muted small">{{ cart.total }} RON</span></li>
                                {% if cart.discount is not null %}
                                <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Coupon "{{ cart.discount.code }}"</strong><span class="text-muted small">-{{ cart.discount.discountAmount(cart.total) }} RON</span></li>
                                {% endif %}
                                <li class="border-bottom my-2"></li>
                                <li class="d-flex align-items-center justify-content-between mb-4"><strong class="text-uppercase small font-weight-bold">Total</strong><span>{{ cart.totalWithDiscount }} RON</span></li>
                                <li>
                                    <strong class="text-uppercase small font-weight-bold">Pick your delivery options</strong>
                                </li>
                                <li>
                                    {{ form_start(orderForm,{
                                    'attr': {'id': 'order_type_form'}
                                    })}}
                                        <div class="input-group mb-2">
                                            {{ form_errors(orderForm.type) }}
{#                                            {{ form_label(orderForm.type) }}#}
                                            {{ form_widget(orderForm.type,{
                                                'attr': {'class': 'form-select'}
                                            }) }}
                                        </div>
                                        <div class="input-group mb-2">
                                            {{ form_errors(orderForm.paymentType) }}
                                            {#                                            {{ form_label(orderForm.paymentType) }}#}
                                            {{ form_widget(orderForm.paymentType,{
                                                'attr': {'class': 'form-select'}
                                            }) }}
                                        </div>
                                    <button class="btn btn-dark btn-sm w-100" type="submit"> <i class="fas fa-pencil me-2"></i>Update delivery and payment</button>
                                    {{ form_end(orderForm) }}
                                </li>
                                <li>
                                    <strong class="text-uppercase small font-weight-bold">Do you have a coupon?</strong>
                                </li>
                                <li>
                                    {{ form_errors(discountForm) }}
                                </li>
                                <li>
                                    {{ form_start(discountForm) }}
                                        <div class="input-group mb-0">

                                            {{ form_widget(discountForm.code,{
                                                attr:{
                                                    class:'form-control',
                                                    placeholder:'Enter your coupon'
                                                }
                                            }) }}
{#                                            <input class="form-control" type="text" placeholder="Enter your coupon">#}
                                            <button class="btn btn-dark btn-sm w-100" type="submit"> <i class="fas fa-gift me-2"></i>Apply coupon</button>
                                        </div>
                                    {{ form_end(discountForm) }}
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        </section>
    </div>
{% endblock %}
{% block javascriptsend %}
    <script src="/js/order.js"></script>
{% endblock %}

templates/products/cart_error.html.twig
{% block form_errors %}
{#    {% spaceless %}#}
        {% if errors|length > 0 %}
            <ul class="list-unstyled ms-1 text-danger">
                {% for error in errors %}
                    <li>{{ error.message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
{#    {% endspaceless %}#}
{% endblock form_errors %}

templates/products/insertproduct.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AddProductController!{% endblock %}

{% block bodystyle %}
style="background-color: black"
{% endblock %}

{% block javascripts %}
{#    {{ encore_entry_script_tags('app') }}#}
{% endblock %}

{% block body %}
<div class="container">
        <h4 class="text-white ms-5 ps-5">Add Product</h4>

        <div class="col-6 ms-5 container-fluid bg-light p-5 pt-4 me-0 rounded">
            <div class="row input-group mb-3 me-0 ms-1">
                <label for="types">Product Types</label>
                <select class="rounded" id="types">
                    <option value="0" disabled selected>Select a type!</option>
                    {% for type in types|keys %}
                        <option value="product_type_{{ loop.index }}">{{ type }}</option>
                    {% endfor %}
                </select>
            </div>
            {% for form in forms%}
                <div id="product_type_{{ loop.index }}" class="form-group justify-content-center" style="display:none;" id="product_type_{{ loop.index }}">
                    {{ form_start(form) }}
                        {% for child in form.children|keys %}
                            <div class="row input-group mb-3 ms-1">
                                {{ form_label(attribute(form.children,child)) }}
                                {{ form_widget(attribute(form.children,child),{ 'attr': {'class': 'rounded'} }) }}
                                {% if child == 'description' %}
                                    <div class="rounded-bottom bg-white me-0" id="editor">
                                        <p>Hello World!</p>
                                        <p>Some initial <strong>bold</strong> text</p>
                                        <p><br></p>
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                    {{ form_end(form) }}
                </div>
            {% endfor %}
        </div>
</div>
{% endblock %}
{% block javascriptsend %}
    <script src="/js/addproduct.js"></script>
{% endblock %}