src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $category_name = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Product::class)]
    private Collection $product;

    public function __construct()
    {
        $this->product = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoryName(): ?string
    {
        return $this->category_name;
    }

    public function setCategoryName(string $category_name): self
    {
        $this->category_name = $category_name;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProduct(): Collection
    {
        return $this->product;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->product->contains($product)) {
            $this->product->add($product);
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->product->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }
}

src/Entity/Option.php
<?php

namespace App\Entity;

use App\Repository\OptionRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OptionRepository::class)]
#[ORM\Table(name: '`option`')]
class Option
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $option_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $option_value = null;

    #[ORM\ManyToOne(inversedBy: 'options')]
    private ?Product $product = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOptionName(): ?string
    {
        return $this->option_name;
    }

    public function setOptionName(string $option_name): self
    {
        $this->option_name = $option_name;

        return $this;
    }

    public function getOptionValue(): ?string
    {
        return $this->option_value;
    }

    public function setOptionValue(?string $option_value): self
    {
        $this->option_value = $option_value;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }
}

templates/element_templates/builder_card.html.twig
{% set card_type = card.category.categoryName | lower %}
{% set card_template = "element_templates/"~card_type~"_card.html.twig" %}
{#<div class="card bg-dark text-light bg-opacity-50" style="width: 16rem;">#}
{#    <img src="{% if card.thumbnail is empty %} https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png {% else %}/thumbnails/{{ card.thumbnail }}{% endif %}" class="card-img-top" alt="...">#}
{#    <div class="card-body">#}
{#        <h5 class="card-title">{{ card.name }}</h5>#}
{#        <p class="card-text">#}
{#            <ul>#}
{#            {% include card_template with {card_type : card}  %}#}
{#            </ul>#}
{#        </p>#}
{#    </div>#}
{#    <button class="btn btn-success purchasebtn" data-uid="{{ card.uid }}"><i class="bi bi-cart-plus-fill"></i> Add To Cart</button>#}
{#</div>#}

<div class="col-md-pcbuilder col-sm-6 {{ card_type }}" data-id="{{ card.uid }}">
    <div class="product-grid">
        <div class="product-image">
            <a href="{{ path('app_product',{id:card.uid}) }}">
                <img class="pic-1" style="height:150px;" src="{% if card.thumbnail is empty %} https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png {% else %}/thumbnails/{{ card.thumbnail }}{% endif %}">
                <img class="pic-2" style="height:150px;" src="{% if card.thumbnail is empty %} https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png {% else %}/thumbnails/{{ card.thumbnail }}{% endif %}">
            </a>
{#            <ul class="social">#}
{#                <li><a href="{{ path('app_product',{id:card.uid}) }}" data-tip="View Page"><i class="bi bi-search"></i></a></li>#}
{#            </ul>#}
{#            <span class="product-new-label">Sale</span>#}
{#            <span class="product-discount-label">20%</span>#}
        </div>
{#        <ul class="rating">#}
{#            <li class="fa fa-star"></li>#}
{#            <li class="fa fa-star"></li>#}
{#            <li class="fa fa-star"></li>#}
{#            <li class="fa fa-star"></li>#}
{#            <li class="fa fa-star disable"></li>#}
{#        </ul>#}
        <div class="product-content">
            <h3 class="title"><a href="{{ path('app_product',{id:card.uid}) }}">{{ card.name }}</a></h3>

            {% include card_template with {card : card.options}  %}
{#            search needs it a bit different, either change the findby for index or make a similar card for search#}
            <div class="price">{{ card.price }} RON
{#                <span>$20.00</span>#}
            </div>
        </div>
    </div>
</div>

templates/element_templates/contact.html.twig
<tr>
    <td class="d-table-cell pname text-truncate" style="max-width: 100px;">{{ contact.name }}</td>
    <td class="d-table-cell text-truncate">{{ contact.country.iso3 }}</td>
    <td class="d-table-cell text-truncate" style="max-width: 100px;">{{ contact.county }}</td>
    <td class="d-table-cell text-truncate" style="max-width: 100px;">{{ contact.city }}</td>
    <td class="d-table-cell text-truncate" style="max-width: 200px;">{{ contact.address }}</td>
    <td class="d-table-cell text-truncate">{{ contact.postalCode }}</td>
    <td class="d-table-cell text-truncate">...{{ contact.phone | slice(-4) }}</td>
    <td class="d-table-cell text-truncate">{{ contact.email | split('@', 2)[0] }}</td>
    <td><a class="btn btn-dark" href="{{ path('app_edit_contact',{id:contact.id}) }}"><i class="bi bi-pencil-square"></i></a>
        <button type="button" class="btn btn-dark conbtn" data-bs-toggle="modal"
                data-id="{{ contact.id }}"
                data-bs-target="#confirmModal"><i class="bi bi-trash"></i></button></td>
</tr>

templates/element_templates/cooler_card.html.twig
{#<li>Tip: {% if cooler.ctype is empty %} N/A {% else %} {{ cooler.ctype }} {% endif %}</li>#}
{#<li>Racire: {% if cooler.cooling == false %} Nu {% else %} Da {% endif %}</li>#}
{#<li>Inaltime: {% if cooler.coolerheight is empty %} N/A {% else %} {{ cooler.coolerheight }} mm {% endif %}</li>#}
{#<li>Numar Ventilatoare: {% if cooler.vents is empty %} N/A {% else %} {{ cooler.vents|length }} {% endif %}</li>#}
{#<li>Dimensiune ventilator: {% if cooler.coolersize is empty %} N/A {% else %} {{ cooler.coolersize }} mm {% endif %}</li>#}
<p class="text-dark-emphasis" style="font-size:0.8rem">{{ card[0].optionValue }} Cooling {{ card[4].optionValue }} x {{ card[2].optionValue }} mm </p>

templates/element_templates/filter_list.html.twig
<li class="mb-2 p-1">
    <h5 id="filterh" data-f="{{ function }}" data-v="{{ value }}" class="text-body-emphasis text-decoration-none">Filtre</h5>
</li>
{% for col_name,col_array in filters %}
<li>
    <h6 class="bg-transparent text-body-emphasis text-decoration-none ms-1">{{ col_name|capitalize }}</h6>
</li>
{#    {{ dump(selected_filters) }}#}
<ul style="list-style: none;">
    {% for filter in col_array %}
    <li>

        <input data-col="{{ col_name }}" value="{{ col_name }}-{{ filter[0] }}" class="filter" type="checkbox">
        <span class="filter_val" class="bg-transparent text-body-emphasis text-decoration-none">{{ filter[0] }}</span><span class="filter_count" class="bg-transparent text-body-emphasis text-decoration-none"> ({{ filter[1] }})</span>
    </li>
    {% endfor %}
</ul>
{% endfor %}

templates/element_templates/gpu_card.html.twig
{#<li>Interfata: {% if gpu.gpuinterface is empty %} N/A {% else %} {{ gpu.gpuinterface }} {% endif %}</li>#}
{#<li>Seria: {% if gpu.series is empty %} N/A {% else %} {{ gpu.series }} {% endif %}</li>#}
{#<li>GPU Boost clock: {% if gpu.clock is empty %} N/A {% else %} {{ gpu.clock }} MHz {% endif %}</li>#}
{#<li>Tip memorie: {% if gpu.gpumemory is empty %} N/A {% else %} {{ gpu.gpumemory }} {% endif %}</li>#}
{#<li>Dimensiune memorie: {% if gpu.gpusize is empty %} N/A {% else %} {{ gpu.gpusize }} GB {% endif %}</li>#}
{#<p class="text-dark-emphasis" style="font-size:0.8rem">{{ card.clock }} MHz {{ card.size }} GB {{ card.memory }}</p>#}
<p class="text-dark-emphasis" style="font-size:0.8rem">{{ card[1].optionValue }} MHz {{ card[3].optionValue }} GB {{ card[2].optionValue }}</p>

templates/element_templates/memory_card.html.twig
{#<li>Tip: {% if mem.memtype is empty %} N/A {% else %} {{ mem.memtype }} {% endif %}</li>#}
{#<li>Capacitate: {% if mem.memcapacity is empty %} N/A {% else %} {{ mem.memcapacity }} GB {% endif %}</li>#}
{#<li>Frecventa: {% if mem.memfrequency is empty %} N/A {% else %} {{ mem.memfrequency }} MHz {% endif %}</li>#}
{#<li>Latenta CAS: {% if mem.latency is empty %} N/A {% else %} {{ mem.latency }} CL {% endif %}</li>#}
<p class="text-dark-emphasis" style="font-size:0.8rem">{{ card[1].optionValue }} GB {{ card[0].optionValue }} {{ card[2].optionValue }} MHz</p>

templates/element_templates/order_items.html.twig
{% for item in cart.items %}
<tr>
  <th class="ps-0 py-3 border-light" scope="row">
    <div class="d-flex align-items-center"><a class="reset-anchor d-block animsition-link" href="{{ path('app_product', {id:item.product.uid}) }}">
      <img src="{% if item.product.thumbnail is empty %} https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png {% else %}/thumbnails/{{ item.product.thumbnail }}{% endif %}" alt="Item Thumbnail" width="70"></a>
      <div class="ms-3"><strong class="h6"><a class="reset-anchor animsition-link" href="{{ path('app_product', {id:item.product.uid}) }}">{{ item.product.name }}</a></strong></div>
    </div>
  </th>
  <td class="p-3 align-middle border-light">
    <p class="mb-0 small">{{ item.product.price }} RON</p>
  </td>
  <td class="p-3 align-middle border-light">
    <div class="border d-flex align-items-center justify-content-between px-3 bg-white q-div">
      {#                                        <div class="me-2 d-none d-md-inline-block col-lg-3"><span class="small text-uppercase text-secondary headings-font-family">Quantity</span></div>#}
      {#                                        FONT FAMILY HAS ISSUES #}
      <button class="btn p-0 col-lg-3 q-dec" data-index="{{ loop.index-1 }}"><i class="fas fa-caret-left"></i></button>
      <div class="col-lg-3">
        <input class="form-control form-control-sm border-0 shadow-0 p-0 text-center q-input bg-white" disabled data-index="{{ loop.index-1 }}" type="number" value="{{ item.quantity }}">
      </div>
      <button class="btn p-0 col-lg-3 q-inc" data-index="{{ loop.index-1 }}"><i class="fas fa-caret-right"></i></button>
    </div>
  </td>
  <td class="p-3 align-middle border-light">
    <p class="mb-0 small">{{ item.total }} RON</p>
  </td>
  <td class="p-3 align-middle border-light order-item"><a class="reset-anchor order-rbtn" href="javascript:void(0)" data-id="{{ item.id }}"><i class="fas fa-trash-alt small text-muted"></i></a></td>
</tr>
{% endfor %}

templates/element_templates/pcbuilder_choice_builds.html.twig
<h4> Generated builds below</h4>
{% for build_key in builds|keys %}
<div class="build" data-key="{{ build_key }}">
    <h4>Build {{ build_key+1 }}</h4>
    <p>Total cost: {{ total_prices[build_key] }} RON</p>
{#    <p></p>#}
    <a class="btn btn-outline-primary build-btn" data-choice="selectedBuild">Select this build</a>
    <div class="row items">
        {%  for component in builds[build_key] %}
            {% if component is not null %}
                {% include 'element_templates/builder_card.html.twig' with {'card': component} %}
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endfor %}

templates/element_templates/pcbuilder_offcanvas_products_table.html.twig
{% for category in categories %}
    <tr id="{{ category.categoryName }}" data-cat-id="{{ category.id }}" class="d-table-row">
        {% if selectedProducts[category.categoryName] is defined %}
            {% if category.id in compatibility_problems|keys %}
                {% include 'element_templates/pcbuilder_selected_products.html.twig' with {item:selectedProducts[category.categoryName],problem:compatibility_problems[category.id]} %}
            {% else %}
                {% include 'element_templates/pcbuilder_selected_products.html.twig' with {item:selectedProducts[category.categoryName]} %}
            {% endif %}
        {% else %}
            {% include 'element_templates/pcbuilder_empty_products.html.twig' with {category_type:category.categoryName}%}
        {% endif %}
    </tr>
{% endfor%}
<tr class="border-bottom-0">
    <td class="border-bottom-0" ></td>
    <td class="border-bottom-0" id="consumptionTotal" >
        {#                                <button class="btn btn-success w-100" data-bs-toggle="modal" data-bs-target="#selectModal"><i class="bi bi-plus-lg"></i>Adauga Componenta</button>#}
        Consumption: {{ consumption_total }} W
    </td>
    <td class="border-bottom-0" id="psuAdvice" >
        {{ psu_advice }}
    </td>
    <td class="border-bottom-0" >
        Pret total:
    </td>
    <td class="border-bottom-0 ms-0" id="priceTotal" >
        {{ price_total }} RON
    </td>
    <td class="border-bottom-0" >
        <a class="btn btn-success w-100" id="add-all-to-cart">Add all to cart</a>
    </td>
</tr>

templates/element_templates/pccase_card.html.twig
{#<li>Tip: {% if case.casetype is empty %} N/A {% else %} {{ case.casetype }} {% endif %}</li>#}
{#<li>Dimensiuni (H x D x W): {% if case.height is empty %} N/A {% else %} {{ case.height }} {% endif %} x {% if case.diameter is empty %} N/A {% else %} {{ case.diameter }} {% endif %} x {% if case.width is empty %} N/A {% else %} {{ case.width }} {% endif %} mm</li>#}
{#<li>Sloturi expansiune: {% if case.slots is empty %} N/A {% else %} x{{ case.slots }} {% endif %}</li>#}
<p class="text-dark-emphasis" style="font-size:0.8rem">{{ card[0].optionValue }} {{ card[1].optionValue }} x {{ card[2].optionValue }} x {{ card[3].optionValue }} mm</p>

templates/element_templates/product_table.html.twig
<h4 class="text-dark col-6">Product List</h4>
{% if products is not empty %}
<div class="table-responsive">
<table class="table table-striped" id="product-table">
    <thead>
    <tr>
        <th scope="col">Thumbnail</th>
        <th scope="col">Name</th>
{#        <th scope="col">Category</th>#}
        {% set product = products|first %}
        {% for option in product.options %}
        <th scope="col">{{ option.optionName|capitalize|replace({'_':' '}) }}</th>
        {% endfor %}
{#        <th scope="col">Consumption</th>#}
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for product in products %}
        <tr class="d-table-row prod-row">
            <td class="d-table-cell">
                <img alt="{{ product.name }}" style="width:128px;height:72px;"src="{% if product.thumbnail is empty%}https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png{% else %}/thumbnails/{{ product.thumbnail }}{% endif %}"/>
            </td>
            <td class="d-table-cell">{{ product.name }}</td>
{#            <td class="d-table-cell">{{ product.category.categoryName }}</td>#}
        {% for option in product.options %}
            {% if option.optionValue is not null %} <td class="d-table-cell text-truncate">{{ option.optionValue }}</td> {% else %} <td class="d-table-cell text-truncate">N/A</td> {% endif %}
        {% endfor %}
            <td class="d-table-cell"><button data-pid="{{ product.id }}" data-cat="{{ product.category.categoryName }}" class="btn btn-primary prod-select{% if product.id == selected_product %} disabled">Selected{% else %} ">Select{% endif %}</button></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</div>
{% else %}
<h1 class="text-center">No products available for this category right now.</h1>
{% endif %}

templates/element_templates/products_generate.html.twig
{% for row in prods|batch(4) %}
<div class="row bg-transparent mt-4">

  {% for prod in row  %}
  {% include 'element_templates/card.html.twig' with {'card': prod} %}
  {% endfor %}
</div>
{% endfor %}

templates/element_templates/ssd_card.html.twig
<p class="text-dark-emphasis" style="font-size:0.8rem">{{ card[2].optionValue }} GB {{ card[3].optionValue }} MB/s max reading</p>

templates/element_templates/user_settings_pcbuilder_template.html.twig
{#{% if app.user.country is not null %}#}
{#    {% set timezone = app.user.country.timezones.0.zoneName%}#}
{#        {% else %}#}
{#    {% set timezone = "Europe/Bucharest" %}#}
{#{% endif %}#}
<tr>
    <td class="d-table-cell">{{ template.uid }}</td>
    <td class="d-table-cell pname text-truncate" style="max-width: 100px;">{{ template.templateName }}</td>
    <td class="d-table-cell">
        {% for item in template.cartItems %}
            <a href="{{ path('app_product',{id:item.product.uid}) }}" class="ms-1 text-decoration-none">{{ item.product.name }}</a>
        {% endfor %}
    </td>
    <td>
        <a class="btn btn-outline-primary" href="{{ path('app_pcbuilder_template',{uid:template.uid}) }}"><i class="bi bi-info-square"></i></a>
        <a class="btn btn-outline-dark" href="{{ path('app_pcbuilder',{uid:template.uid}) }}"><i class="bi bi-pencil-square"></i></a>
        <button type="button" class="btn btn-outline-danger conbtnp" data-bs-toggle="modal"
                data-id="{{ template.uid }}"
                data-bs-target="#confirmModalTemplate"><i class="bi bi-trash"></i></button></td>
</tr>